### ISSUE TITLE
The image changes permissions when mounting the host `docker.sock` into the container.

### ISSUE THREAD

**Issue by taylordaughtry** [tcardonne/docker-github-runner#10]
First: thanks for making this image; it's been extremely handy to get up and running with self-hosted runners.

I do have one request: would it be possible to remove the permissions change here?
https://github.com/tcardonne/docker-github-runner/blob/861abc39c7e6a56c1211ac744b5e4a09696f13e9/debian-buster/entrypoint.sh#L5

Since docker-in-docker isn't advised, the "best-practice" solution is to mount the host's docker socket into the container. (You note this in the README and provide the solution: `-v /var/run/docker.sock:/var/run/docker.sock`).

However, doing so will cause permissions on the host docker socket to change, as a result of the linked command above.

This is the _only_ thing preventing us from using your image on a larger-scale, so if you have any questions/clarifications here I'd be glad to answer them!

Thanks again!

**Comment by missedone** [comment]
i think it is caused by this line in Dockerfile: https://github.com/tcardonne/docker-github-runner/blob/master/debian-buster/Dockerfile#L66

the fix could be remove this line, and add switch user in entrypoint.sh

**Comment by missedone** [comment]
or, similar as above, remove https://github.com/tcardonne/docker-github-runner/blob/master/debian-buster/Dockerfile#L66

and add flag allows starting the runner with env `RUNNER_ALLOW_RUNASROOT=true`, see also: https://github.com/actions/runner/pull/227

**Comment by tcardonne** [comment]
Hello,

This was a silly workaround, so I changed the image to run the runner as root instead of using a dedicated user (which had sudo privileges anyway).

I've changed that in the master branch (https://github.com/tcardonne/docker-github-runner/commit/90ae74aa0c02aae17d32647637a3add33736ebd1), but I will tag a new release later this week-end.

In the meantime, can you tell me if this solution would fit your needs?

**Comment by tcardonne** [comment]
Implemented in v1.2.0 🚀
