### ISSUE TITLE
Container is shut down when automatically updating github runner

### ISSUE THREAD

**Issue by kei-yamazaki** [tcardonne/docker-github-runner#2]
Thank you for the useful code.

The github runner seems to check for the latest version when running a job.
If the latest version is available, the runner will be updated automatically, but the container will stop because container entry point is run.sh and it will exit.

Following is the container output when updating automatically
```
Runner update in progress, do not shutdown runner.
Downloading 2.161.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should back online within 10 seconds.
```
Although the version is specified, I think that it is necessary to check the latest version every time it starts or to have a mechanism that monitors the process of run.sh.
https://github.com/tcardonne/docker-github-runner/blob/d29b46792b2a3551b22dfde097b97019276c01c0/debian-buster/Dockerfile#L3

**Comment by tcardonne** [comment]
Hi,

Thanks for your feedback. I ran into this issue a few days ago. I was not aware of this behavior and I was expecting some kind of back-compatibility.

I will try to provide a fix as soon as possible for this issue, probably by implementing some kind of process supervision. I suppose that checking the last version at the entrypoint level is not sufficient, given that we don't know the runner's behavior when an updated is released (ie, will the runner install the update automatically?)

I'll also try to tag the Docker images in a more granular way, instead of using just `latest`.

Best regards

**Comment by tcardonne** [comment]
The issue should be fixed on the latest Docker image.
During testing, I've noticed that the runner is made aware of any update when a new job is queued.

I will bump the version number in an upcoming update.

**Comment by kei-yamazaki** [comment]
Thanks for quick response and fix.

It works perfectly with the latest commits.
